swagger: "2.0"
info:
  title: Shopping Cart
  version: 0.1.0
host: localhost:7009
schemes:
  - http
paths:
  /api/v1/users/login:
    post:
      tags:
        - "auth"
      summary: "Login user"
      description: "Login user"
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "UserCredentials object"
        required: true
        schema:
          $ref: "#/definitions/UserCredentials"
      responses:
        "200":
          description: "The used was successfully logged in"
          schema:
            $ref: "#/definitions/Token"
        "401":
          description: "The user is Unauthorized"
  /api/v1/users/logout:
    get:
      tags:
        - "auth"
      summary: "Logout user"
      description: "Logout user"
      operationId: "logout"
      consumes:
      - "application/json"
      responses:
        "200":
          description: "The used was successfully logged out"
        "401":
          description: "The user is Unauthorized"
  /api/v1/carts/add:
    post:
      tags:
        - "carts"
      summary: "Added products in cart"
      description: "Added products in cart"
      operationId: "addToCarts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cart Element object added into cart"
        required: true
        schema:
          $ref: "#/definitions/CartElement"
      responses:
        "200":
          description: "The used was successfully logged in"
          schema:
            $ref: "#/definitions/Token"
        "401":
          description: "The user is Unauthorized" 
        "404":
          description: "The stock is not enought"
  /api/v1/carts/checkout:
    get:
      tags:
        - "carts"
      summary: "Finish the shopping and checkout cart"
      description: "Finish the shopping and checkout cart"
      operationId: "order"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cart Element object added into cart"
        required: true
        schema:
          $ref: "#/definitions/CartElement"
      responses:
        "200":
          description: "The used was successfully logged in"
          schema:
            $ref: "#/definitions/Token"
        "401":
          description: "The user is Unauthorized" 
        "404":
          description: "The stock is not enought"      
definitions:
  UserCredentials:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  Token:
    type: object
    required:
      - token
    properties:
      token:
        type: string
  CartElement:
    type: object
    required:
      - product_id
      - quantity
    properties:
      product_id:
        type: string
      quantity:
        type: string
